// <auto-generated />
namespace BloggingApplication.DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addeduseridandcategoryidinpost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeduseridandcategoryidinpost));
        
        string IMigrationMetadata.Id
        {
            get { return "201707100639331_added userid and categoryid in post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
